version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api-service:
    build: ./api-service
    ports:
      - "3000:3000"
    depends_on:
      - db

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - api-service
